name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run linting
      run: |
        pre-commit run --all-files

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run integration tests
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
        TEST_GITHUB_ORG: ${{ secrets.TEST_GITHUB_ORG }}
      run: |
        if [ -z "$TEST_GITHUB_TOKEN" ] || [ -z "$TEST_GITHUB_ORG" ]; then
          echo "ERROR: Required secrets TEST_GITHUB_TOKEN and TEST_GITHUB_ORG must be set"
          echo "Please configure these secrets in your repository settings"
          exit 1
        fi

        # Run the integration tests
        pytest tests/integration/ -xvs