name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run unit tests
      run: |
        pytest tests/ -k "not integration"
    - name: Run linting
      run: |
        pre-commit run --all-files

  integration-tests:
    runs-on: ubuntu-latest
    # Only run integration tests on main branch or when explicitly requested with label
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run-integration-tests')

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run integration tests
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
        TEST_GITHUB_ORG: ${{ secrets.TEST_GITHUB_ORG }}
      run: |
        # Skip these tests if the required secrets are not available
        if [ -z "$TEST_GITHUB_TOKEN" ] || [ -z "$TEST_GITHUB_ORG" ]; then
          echo "Skipping integration tests because required secrets are not set"
          exit 0
        fi

        # Run the integration tests
        pytest tests/integration/ -xvs